'use client';
import { useEffect, useState } from 'react';
import { supabase } from '../../../lib/supabase';
import IndustryPicker from '../../../components/IndustryPicker';
import { US_STATES } from '../../../lib/us-states';

export default function SellerOnboardingPage() {
  const [user,setUser] = useState(null); const [fullName,setFullName] = useState(''); const [name,setName] = useState(''); const [industry,setIndustry] = useState(''); const [description,setDescription] = useState(''); const [startDate,setStartDate] = useState(''); const [askingPrice,setAskingPrice] = useState(''); const [city,setCity] = useState(''); const [state,setState] = useState(''); const [zip,setZip] = useState(''); const [keywords,setKeywords] = useState(''); const [msg,setMsg] = useState(''); const [saving,setSaving] = useState(false);
  useEffect(() => { (async () => { if (!supabase) return; const {data:{user:current}}=await supabase.auth.getUser(); setUser(current||null); if (!current) return; const {data}=await supabase.from('profiles').select('full_name').eq('id',current.id).maybeSingle(); setFullName(data?.full_name||current.email||''); })(); },[]);
  async function save(e) { e.preventDefault(); if (!supabase || !user) return setMsg('Please sign in first.'); const price=Number(String(askingPrice).replace(/[^\d.]/g,'')); if (!startDate) return setMsg('Add the date the business started.'); if (!Number.isFinite(price) || price <= 0) return setMsg('Add a valid asking price.'); setSaving(true); setMsg(''); const {error:profileError}=await supabase.from('profiles').upsert({id:user.id,full_name:fullName,role:'seller',seller_notes:`Business: ${name}\nIndustry: ${industry}\nLocation: ${[city,state,zip].filter(Boolean).join(', ')}`}); if (profileError) {setSaving(false);return setMsg(profileError.message);} const {data:business,error}=await supabase.from('businesses').insert({name:name.trim(),industry:industry.trim(),description:description.trim(),category:'established',start_date:startDate,default_asking_price:price,city:city.trim()||null,state:state||null,zip:zip.trim()||null,country:'United States',keywords:keywords.split(',').map(x=>x.trim()).filter(Boolean),created_by:user.id,status:'approved'}).select('id').single(); if(error){setSaving(false);return setMsg(error.message);} const {error:memberError}=await supabase.from('business_memberships').upsert({business_id:business.id,user_id:user.id,role:'Owner',is_admin:true,status:'approved'},{onConflict:'business_id,user_id'}); setSaving(false); if(memberError) return setMsg(memberError.message); window.location.assign(`/listings/new?business=${business.id}`); }
  return <main className='onboarding-shell'><div className='onboarding-progress'><span className='is-done'/><span className='is-done'/><span/></div><section className='onboarding-card'><p className='account-kicker'>Seller setup · Step 2 of 3</p><h1>Build your business profile.</h1><p className='onboarding-copy'>Create it once, keep its details in one place, and use it for every listing you publish.</p><form className='onboarding-form' onSubmit={save}><label>Your name<input value={fullName} onChange={e=>setFullName(e.target.value)} required /></label><label>Business name<input value={name} onChange={e=>setName(e.target.value)} placeholder='e.g. Acme Supply Co.' required /></label><label>Industry<IndustryPicker value={industry} onChange={setIndustry} required /></label><label>What does the business do?<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder='A concise, buyer-ready overview.' required /></label><div className='onboarding-row'><label>Business started<input type='date' value={startDate} onChange={e=>setStartDate(e.target.value)} required /></label><label>Asking price<input inputMode='decimal' value={askingPrice} onChange={e=>setAskingPrice(e.target.value)} placeholder='$250,000' required /></label></div><p className='onboarding-copy'>We calculate business age from the start date, so buyers can filter startups (0–1 years), newer businesses, and established operators accurately.</p><div className='onboarding-row'><label>City<input value={city} onChange={e=>setCity(e.target.value)} placeholder='Miami' /></label><label>State<select value={state} onChange={e=>setState(e.target.value)}><option value=''>Choose state</option>{US_STATES.map(s=><option value={s} key={s}>{s}</option>)}</select></label></div><div className='onboarding-row'><label>ZIP code<input value={zip} onChange={e=>setZip(e.target.value)} placeholder='33101' /></label><label>Search keywords<input value={keywords} onChange={e=>setKeywords(e.target.value)} placeholder='commercial cleaning, B2B, recurring revenue' /></label></div><div className='onboarding-actions'><button disabled={saving} type='submit'>{saving?'Creating business…':'Create business & continue'}</button><a href='/dashboard'>Save for later</a></div>{msg?<p className='onboarding-status' role='status'>{msg}</p>:null}</form></section></main>;
}
