'use client';
import { useEffect, useState } from 'react';
import { supabase } from '../../../lib/supabase';
import IndustryPicker from '../../../components/IndustryPicker';
import { US_STATES } from '../../../lib/us-states';

const types = [['established','Established business','An operating company ready for its next owner.'],['asset_sale','Asset sale','Equipment, inventory, IP, or a carve-out.'],['real_estate','Real estate','A property-led opportunity.'],['startup','Startup','An early-stage business or venture.']];
export default function SellerOnboardingPage() {
  const [user,setUser] = useState(null); const [fullName,setFullName] = useState(''); const [name,setName] = useState(''); const [industry,setIndustry] = useState(''); const [description,setDescription] = useState(''); const [category,setCategory] = useState('established'); const [city,setCity] = useState(''); const [state,setState] = useState(''); const [zip,setZip] = useState(''); const [keywords,setKeywords] = useState(''); const [msg,setMsg] = useState(''); const [saving,setSaving] = useState(false);
  useEffect(() => { (async () => { if (!supabase) return; const {data:{user:current}}=await supabase.auth.getUser(); setUser(current||null); if (!current) return; const {data}=await supabase.from('profiles').select('full_name').eq('id',current.id).maybeSingle(); setFullName(data?.full_name||current.email||''); })(); },[]);
  async function save(e) { e.preventDefault(); if (!supabase || !user) return setMsg('Please sign in first.'); setSaving(true); setMsg(''); const {error:profileError}=await supabase.from('profiles').upsert({id:user.id,full_name:fullName,role:'seller',seller_notes:`Business: ${name}\nIndustry: ${industry}\nLocation: ${[city,state,zip].filter(Boolean).join(', ')}`}); if (profileError) {setSaving(false);return setMsg(profileError.message);} const {data:business,error}=await supabase.from('businesses').insert({name:name.trim(),industry:industry.trim(),description:description.trim(),category,city:city.trim()||null,state:state||null,zip:zip.trim()||null,country:'United States',keywords:keywords.split(',').map(x=>x.trim()).filter(Boolean),created_by:user.id,status:'approved'}).select('id').single(); if(error){setSaving(false);return setMsg(error.message);} const {error:memberError}=await supabase.from('business_memberships').upsert({business_id:business.id,user_id:user.id,role:'Owner',is_admin:true,status:'approved'},{onConflict:'business_id,user_id'}); setSaving(false); if(memberError) return setMsg(memberError.message); window.location.assign(`/listings/new?business=${business.id}`); }
  return <main className='onboarding-shell'><div className='onboarding-progress'><span className='is-done'/><span className='is-done'/><span/></div><section className='onboarding-card'><p className='account-kicker'>Seller setup · Step 2 of 3</p><h1>Build your business profile.</h1><p className='onboarding-copy'>Create it once, keep its details in one place, and use it for every listing you publish.</p><form className='onboarding-form' onSubmit={save}><label>Your name<input value={fullName} onChange={e=>setFullName(e.target.value)} required /></label><label>Business name<input value={name} onChange={e=>setName(e.target.value)} placeholder='e.g. Acme Supply Co.' required /></label><label>Industry<IndustryPicker value={industry} onChange={setIndustry} required /></label><label>What does the business do?<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder='A concise, buyer-ready overview.' required /></label><div><p className='account-kicker'>Opportunity type</p><div className='onboarding-options'>{types.map(([value,label,note])=><button className={category===value?'is-active':''} onClick={()=>setCategory(value)} type='button' key={value}><strong>{label}</strong><span>{note}</span></button>)}</div></div><div className='onboarding-row'><label>City<input value={city} onChange={e=>setCity(e.target.value)} placeholder='Miami' /></label><label>State<select value={state} onChange={e=>setState(e.target.value)}><option value=''>Choose state</option>{US_STATES.map(s=><option value={s} key={s}>{s}</option>)}</select></label></div><div className='onboarding-row'><label>ZIP code<input value={zip} onChange={e=>setZip(e.target.value)} placeholder='33101' /></label><label>Search keywords<input value={keywords} onChange={e=>setKeywords(e.target.value)} placeholder='commercial cleaning, B2B, recurring revenue' /></label></div><div className='onboarding-actions'><button disabled={saving} type='submit'>{saving?'Creating business…':'Create business & continue'}</button><a href='/dashboard'>Save for later</a></div>{msg?<p className='onboarding-status' role='status'>{msg}</p>:null}</form></section></main>;
}
