'use client';

import { useEffect, useState } from 'react';
import { supabase } from '../../lib/supabase';

const roles = [['buyer','Buyer'],['seller','Seller'],['broker','Broker'],['not_sure','Exploring']];

export default function ProfilePage() {
  const [user,setUser] = useState(null), [fullName,setFullName] = useState(''), [email,setEmail] = useState(''), [handle,setHandle] = useState(''), [phone,setPhone] = useState(''), [role,setRole] = useState('buyer'), [avatarUrl,setAvatarUrl] = useState(''), [avatarFile,setAvatarFile] = useState(null), [message,setMessage] = useState(''), [saving,setSaving] = useState(false);
  useEffect(() => { async function load() { if (!supabase) return; const { data } = await supabase.auth.getUser(); const account = data?.user; setUser(account || null); if (!account) return; setEmail(account.email || ''); const { data: profile } = await supabase.from('profiles').select('full_name,handle,phone,role,avatar_url').eq('id',account.id).single(); if (profile) { setFullName(profile.full_name || ''); setHandle(profile.handle || ''); setPhone(profile.phone || ''); setRole(profile.role || 'buyer'); setAvatarUrl(profile.avatar_url || ''); } } load(); },[]);
  async function save(e) { e.preventDefault(); if (!supabase || !user) return setMessage('Sign in to edit your profile.'); setSaving(true); setMessage(''); let nextAvatar = avatarUrl || null; if (avatarFile) { const ext = avatarFile.name.split('.').pop(); const path = `${user.id}/avatar-${Date.now()}.${ext}`; const upload = await supabase.storage.from('profile-photos').upload(path,avatarFile); if (upload.error) { setSaving(false); return setMessage(upload.error.message); } nextAvatar = supabase.storage.from('profile-photos').getPublicUrl(path).data.publicUrl; } if (email && email !== user.email) { const { error } = await supabase.auth.updateUser({email}); if (error) { setSaving(false); return setMessage(error.message); } } const cleanHandle = handle.trim() ? handle.trim().toLowerCase() : null; const { error } = await supabase.from('profiles').upsert({id:user.id,full_name:fullName,handle:cleanHandle,phone,role,avatar_url:nextAvatar}); setSaving(false); if (error) return setMessage(error.message.includes('profiles_handle_key') ? 'That handle is already taken. Try a different one.' : error.message); setAvatarUrl(nextAvatar || ''); setHandle(cleanHandle || ''); setMessage('Your profile is live.'); }
  if (!user) return <main className="profile-shell"><section className="profile-empty"><p className="account-kicker">Your account</p><h1>Set up your GoDyrect profile.</h1><p>Sign in to add the details people see when you message, list, or follow a business.</p><a className="account-primary" href="/login?returnTo=%2Fprofile">Sign in</a></section></main>;
  const initial = (fullName || email || '?').trim().charAt(0).toUpperCase();
  return <main className="profile-shell"><header className="profile-heading"><div><p className="account-kicker">Your account</p><h1>Your professional profile.</h1><p>Keep your identity clear and credible across every conversation and listing.</p></div><a href="/businesses" className="home-hero__secondary">Manage businesses</a></header><form className="profile-grid" onSubmit={save}><aside className="profile-identity"><div className="profile-avatar">{avatarUrl ? <img src={avatarUrl} alt="Profile" /> : <span>{initial}</span>}</div><strong>{fullName || 'Your name'}</strong><span>{roles.find(([key]) => key === role)?.[1]}</span><label className="profile-photo"><input type="file" accept="image/*" onChange={(e) => setAvatarFile(e.target.files?.[0] || null)} />Change photo</label></aside><section className="profile-form"><div className="section-heading"><div><p className="account-kicker">Public details</p><h2>Make the introduction count.</h2></div>{message ? <span className="profile-status">{message}</span> : null}</div><div className="profile-fields"><label>Display name<input placeholder="e.g. Jordan Lee" value={fullName} onChange={(e) => setFullName(e.target.value)} /></label><label>Profile handle<input placeholder="e.g. jordanlee" value={handle} onChange={(e) => setHandle(e.target.value)} /></label><label>Email address<input type="email" placeholder="you@company.com" value={email} onChange={(e) => setEmail(e.target.value)} /></label><label>Phone number <small>Optional</small><input placeholder="e.g. (305) 555-0147" value={phone} onChange={(e) => setPhone(e.target.value)} /></label></div><fieldset className="profile-role"><legend>How do you use GoDyrect?</legend><div>{roles.map(([key,label]) => <button type="button" className={role === key ? 'is-active' : ''} onClick={() => setRole(key)} key={key}>{label}</button>)}</div></fieldset><div className="profile-actions"><button className="account-primary" disabled={saving} type="submit">{saving ? 'Saving…' : 'Save profile'}</button><a href="/settings">Account settings</a></div></section></form></main>;
}
