'use client';
import { useEffect, useState } from 'react';
import { supabase } from '../../lib/supabase';

const modes = [['buyer','Buyer','Find and save opportunities.'],['seller','Seller','Present a business with confidence.'],['broker','Broker','Manage represented opportunities.'],['not_sure','Exploring','Keep both paths open for now.']];

export default function SettingsPage() {
  const [user,setUser] = useState(null); const [role,setRole] = useState('not_sure'); const [message,setMessage] = useState(''); const [acknowledged,setAcknowledged] = useState(false); const [deleting,setDeleting] = useState(false); const [isNativeApp,setIsNativeApp] = useState(false);
  useEffect(() => { setIsNativeApp(Boolean(window.GoDyrectNative)); (async () => { if (!supabase) return; const { data: auth } = await supabase.auth.getUser(); const current = auth?.user || null; setUser(current); if (!current) return; const { data } = await supabase.from('profiles').select('role').eq('id',current.id).maybeSingle(); setRole(data?.role || 'not_sure'); })(); },[]);
  async function saveRole(next) { if (!supabase || !user) return setMessage('Please sign in first.'); setMessage(''); const { error } = await supabase.from('profiles').upsert({ id:user.id, role:next }); if (error) return setMessage(error.message); setRole(next); setMessage('Your workspace is updated.'); }
  async function signOut() { const { error } = await supabase.auth.signOut(); if (error) return setMessage(error.message); window.location.assign('/explore'); }
  async function deleteAccount() { if (!supabase || !user || !acknowledged || deleting) return; if (!window.confirm('Delete your GoDyrect account and all associated marketplace data? This cannot be undone.')) return; setDeleting(true); setMessage('Deleting your account…'); const { error } = await supabase.functions.invoke('delete-account',{ body:{ confirm:true } }); if (error) { setDeleting(false); return setMessage(error.message || 'We could not delete your account. Please try again.'); } await supabase.auth.signOut(); window.location.assign('/goodbye'); }
  if (!user) return <main className='account-shell'><section className='account-panel account-panel--narrow'><p className='account-kicker'>Account</p><h1>Sign in to manage your space.</h1><p className='account-lede'>Your profile, preferences, and privacy controls live here.</p><a href='/login?returnTo=%2Fsettings' className='account-primary'>Sign in</a></section></main>;
  return <main className='account-shell'>
    <section className='account-heading'><p className='account-kicker'>Account studio</p><h1>Make it yours.</h1><p className='account-lede'>A quieter control room for the way you use GoDyrect.</p></section>
    <div className='account-layout'><section className='account-panel account-panel--main'><div className='section-heading'><div><p className='account-kicker'>Your mode</p><h2>What brings you here?</h2></div><a href='/profile' className='account-text-link'>Edit profile →</a></div><div className='mode-grid'>{modes.map(([value,label,note]) => <button key={value} type='button' onClick={() => saveRole(value)} className={`mode-card ${role === value ? 'is-active' : ''}`}><strong>{label}</strong><span>{note}</span><i>{role === value ? 'Selected' : 'Choose'}</i></button>)}</div>{message ? <p className='account-status' role='status'>{message}</p> : null}</section>
      <aside className='account-stack'><section className='account-panel account-panel--compact'><p className='account-kicker'>Profile & security</p><h2>Keep your account current.</h2><div className='account-links'><a href='/profile'>Profile, email & phone <span>→</span></a><a href='/forgot-password'>Reset password <span>→</span></a>{isNativeApp ? <button type='button' className='account-link-button' onClick={() => window.GoDyrectNative?.request?.('notificationPreferences')}>Notification preferences <span>→</span></button> : null}</div></section><section className='account-panel account-panel--compact'><p className='account-kicker'>Workspace</p><h2>Useful shortcuts</h2><div className='account-links'><a href='/businesses'>Businesses <span>→</span></a><a href='/listings'>Listings <span>→</span></a><a href='/favorites'>Saved opportunities <span>→</span></a><a href='/messages'>Messages <span>→</span></a></div></section><section className='account-panel account-panel--compact'><p className='account-kicker'>Privacy</p><h2>You are in control.</h2><p className='account-copy'>Read exactly what we collect, how social sign-in works, and how to remove your data.</p><a className='account-text-link' href='/legal/privacy'>Read privacy & terms →</a></section></aside></div>
    <section id='delete-account' className='danger-zone'><div><p className='account-kicker'>Account deletion</p><h2>Leave GoDyrect</h2><p>Deleting your account permanently removes your profile, listings, businesses you created, saved opportunities, follows, messages, and uploaded marketplace media.</p></div><div className='danger-zone__action'><label><input type='checkbox' checked={acknowledged} onChange={e => setAcknowledged(e.target.checked)} /> I understand this cannot be undone.</label><button type='button' onClick={deleteAccount} disabled={!acknowledged || deleting}>{deleting ? 'Deleting account…' : 'Delete my account'}</button></div></section>
    <button type='button' className='signout-button' onClick={signOut}>Sign out</button></main>;
}
